export const list = [
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/4bof0ZfFsgSQ9A3519zfvC',
        },
        href: 'https://api.spotify.com/v1/playlists/4bof0ZfFsgSQ9A3519zfvC',
        id: '4bof0ZfFsgSQ9A3519zfvC',
        name: 'july_repeat_everything',
        primary_color: null,
        public: true,
        snapshot_id: 'MTAsZmYwNTJlMDllN2VlY2RmNGVlNWU0NDBhYzIyY2RiMDdmZmEwMzY3YQ==',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/4bof0ZfFsgSQ9A3519zfvC/tracks',
            total: 37,
        },
        type: 'playlist',
        uri: 'spotify:playlist:4bof0ZfFsgSQ9A3519zfvC',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/03de8Phg9jBojkrhxQX9LE',
        },
        href: 'https://api.spotify.com/v1/playlists/03de8Phg9jBojkrhxQX9LE',
        id: '03de8Phg9jBojkrhxQX9LE',
        name: 'B&L Fresh Batch',
        primary_color: null,
        public: false,
        snapshot_id: 'MTA0Niw5YjlkNGVlMGI2OTFmOWFmNWI5YTA1Njc0ZmI5ZGNmYjdiOWQ0MjNh',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/03de8Phg9jBojkrhxQX9LE/tracks',
            total: 106,
        },
        type: 'playlist',
        uri: 'spotify:playlist:03de8Phg9jBojkrhxQX9LE',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/7zt6XcebGDPj9weCyjbcSf',
        },
        href: 'https://api.spotify.com/v1/playlists/7zt6XcebGDPj9weCyjbcSf',
        id: '7zt6XcebGDPj9weCyjbcSf',
        name: 'new new new',
        primary_color: null,
        public: true,
        snapshot_id: 'MzEsMTQyOGVjZTkzMDc3ZTFmM2JmMDc5MGNkMWFmZTFkNTMyZGI4NGE0NA==',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/7zt6XcebGDPj9weCyjbcSf/tracks',
            total: 1768,
        },
        type: 'playlist',
        uri: 'spotify:playlist:7zt6XcebGDPj9weCyjbcSf',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/3bdLrIgRSwO6q7x3cBDNkj',
        },
        href: 'https://api.spotify.com/v1/playlists/3bdLrIgRSwO6q7x3cBDNkj',
        id: '3bdLrIgRSwO6q7x3cBDNkj',
        name: 'favorite artists',
        primary_color: null,
        public: true,
        snapshot_id: 'MTAyMCwwOTkyMzM2YTEyZmRhYWFlMmE1NDFiZTBkYzI5ZDViMDI3MTQzMTdi',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/3bdLrIgRSwO6q7x3cBDNkj/tracks',
            total: 905,
        },
        type: 'playlist',
        uri: 'spotify:playlist:3bdLrIgRSwO6q7x3cBDNkj',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/6G1wrNVfTlxYEW5gdzCsCg',
        },
        href: 'https://api.spotify.com/v1/playlists/6G1wrNVfTlxYEW5gdzCsCg',
        id: '6G1wrNVfTlxYEW5gdzCsCg',
        name: 'shit i really like',
        primary_color: null,
        public: true,
        snapshot_id: 'NDI1LDZlNzNmODBhMjI4ZDU5MzQ2MGVhZTc1MTEzYzZhMDg5NzcyZTQ1NzY=',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/6G1wrNVfTlxYEW5gdzCsCg/tracks',
            total: 1275,
        },
        type: 'playlist',
        uri: 'spotify:playlist:6G1wrNVfTlxYEW5gdzCsCg',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/3qcApm9ubHd20znliLR2B8',
        },
        href: 'https://api.spotify.com/v1/playlists/3qcApm9ubHd20znliLR2B8',
        id: '3qcApm9ubHd20znliLR2B8',
        name: 'finals szn',
        primary_color: null,
        public: false,
        snapshot_id: 'MTU5LDMwOTUwMDlhNjIzYTFlNWIzNjBmNmIzNjkxMDE1MTdhOTEwMmFmM2U=',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/3qcApm9ubHd20znliLR2B8/tracks',
            total: 108,
        },
        type: 'playlist',
        uri: 'spotify:playlist:3qcApm9ubHd20znliLR2B8',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/3cG0NOvsCTAq0391ctZQqg',
        },
        href: 'https://api.spotify.com/v1/playlists/3cG0NOvsCTAq0391ctZQqg',
        id: '3cG0NOvsCTAq0391ctZQqg',
        name: 'how to get thruuuu finals',
        primary_color: null,
        public: false,
        snapshot_id: 'MjAxLDk1MmIzNmNiMzhlOTZmYzIwZDJiMTM4MjA3ZGNjNmZiMjFkNWJhNzI=',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/3cG0NOvsCTAq0391ctZQqg/tracks',
            total: 118,
        },
        type: 'playlist',
        uri: 'spotify:playlist:3cG0NOvsCTAq0391ctZQqg',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/37i9dQZEVXcHUjGPohFrdd',
        },
        href: 'https://api.spotify.com/v1/playlists/37i9dQZEVXcHUjGPohFrdd',
        id: '37i9dQZEVXcHUjGPohFrdd',
        name: 'Discover Weekly',
        primary_color: null,
        public: false,
        snapshot_id: 'MjYxNDMyMDAsMDAwMDAwMDAyZDBiZmZhZTVmYzA5YmJiMDM4MjM1NDkyYWNhYTk5YQ==',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/37i9dQZEVXcHUjGPohFrdd/tracks',
            total: 30,
        },
        type: 'playlist',
        uri: 'spotify:playlist:37i9dQZEVXcHUjGPohFrdd',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/0xt63vcfSFSZ4xcKRsdRFJ',
        },
        href: 'https://api.spotify.com/v1/playlists/0xt63vcfSFSZ4xcKRsdRFJ',
        id: '0xt63vcfSFSZ4xcKRsdRFJ',
        name: 'chill w dat',
        primary_color: null,
        public: true,
        snapshot_id: 'Nzg3LGU0ZGIwZjgyNmI0MmMyNWRhZmMxMGM3YWUzN2Q2MmIwNGYyODg5NTU=',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/0xt63vcfSFSZ4xcKRsdRFJ/tracks',
            total: 377,
        },
        type: 'playlist',
        uri: 'spotify:playlist:0xt63vcfSFSZ4xcKRsdRFJ',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/3jXQJ6HXUfbYxARyN2DaSZ',
        },
        href: 'https://api.spotify.com/v1/playlists/3jXQJ6HXUfbYxARyN2DaSZ',
        id: '3jXQJ6HXUfbYxARyN2DaSZ',
        name: '党',
        primary_color: null,
        public: false,
        snapshot_id: 'MTc5LGU3ZTAwMDJjODdiNTUxZDAzZDM1Y2NiYWNkYmJiNmYzMGRiMzkyOWU=',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/3jXQJ6HXUfbYxARyN2DaSZ/tracks',
            total: 127,
        },
        type: 'playlist',
        uri: 'spotify:playlist:3jXQJ6HXUfbYxARyN2DaSZ',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/7Azn8R8udy7T4nVG1mC6yi',
        },
        href: 'https://api.spotify.com/v1/playlists/7Azn8R8udy7T4nVG1mC6yi',
        id: '7Azn8R8udy7T4nVG1mC6yi',
        name: 'Cashmere Cat Complete',
        primary_color: null,
        public: false,
        snapshot_id: 'MjQwOCwxMDkxNjA4Y2Q2MmYyMjg2MDYzYmFmMzFmMGFmMTdkYzIzNmY3ZmM0',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/7Azn8R8udy7T4nVG1mC6yi/tracks',
            total: 33,
        },
        type: 'playlist',
        uri: 'spotify:playlist:7Azn8R8udy7T4nVG1mC6yi',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/2uhpfOIVrJIkl5kb4ujXHc',
        },
        href: 'https://api.spotify.com/v1/playlists/2uhpfOIVrJIkl5kb4ujXHc',
        id: '2uhpfOIVrJIkl5kb4ujXHc',
        name: 'Galantis FM',
        primary_color: null,
        public: false,
        snapshot_id: 'MTk1OCw4NmNjOTk2NzU2YmI2ZTRjNzM5OGNkZjdiMmJjZGExYmZjOGYyZDkx',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/2uhpfOIVrJIkl5kb4ujXHc/tracks',
            total: 67,
        },
        type: 'playlist',
        uri: 'spotify:playlist:2uhpfOIVrJIkl5kb4ujXHc',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/6AvLNaeJ7qeF1Ur1kNoiXT',
        },
        href: 'https://api.spotify.com/v1/playlists/6AvLNaeJ7qeF1Ur1kNoiXT',
        id: '6AvLNaeJ7qeF1Ur1kNoiXT',
        name: 'Diplo and Friends Radio',
        primary_color: null,
        public: false,
        snapshot_id: 'MzMyMSwxZTNhNWNjMDMyMmVhYWI0NmRjNDdlZThkMTVjZDg2OTI0ZDgyY2Nm',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/6AvLNaeJ7qeF1Ur1kNoiXT/tracks',
            total: 158,
        },
        type: 'playlist',
        uri: 'spotify:playlist:6AvLNaeJ7qeF1Ur1kNoiXT',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/37i9dQZF1DWSfMe9z89s9B',
        },
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWSfMe9z89s9B',
        id: '37i9dQZF1DWSfMe9z89s9B',
        name: 'Alternative R&B',
        primary_color: null,
        public: false,
        snapshot_id: 'MTU3MTQzNzU5OCwwMDAwMDBhMjAwMDAwMTZkZTBmYWQ2MGQwMDAwMDE2ZDAwYWVlMmU3',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DWSfMe9z89s9B/tracks',
            total: 140,
        },
        type: 'playlist',
        uri: 'spotify:playlist:37i9dQZF1DWSfMe9z89s9B',
    },
    {
        collaborative: false,
        external_urls: {
            spotify: 'https://open.spotify.com/playlist/37i9dQZF1DX44t7uCdkV1A',
        },
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX44t7uCdkV1A',
        id: '37i9dQZF1DX44t7uCdkV1A',
        name: 'Viral Hits',
        primary_color: null,
        public: false,
        snapshot_id: 'MTU2NzY3NjM4OSwwMDAwMDA0YTAwMDAwMTY1N2JmNTkzZTkwMDAwMDE2ZDAwY2I1OGI5',
        tracks: {
            href: 'https://api.spotify.com/v1/playlists/37i9dQZF1DX44t7uCdkV1A/tracks',
            total: 25,
        },
        type: 'playlist',
        uri: 'spotify:playlist:37i9dQZF1DX44t7uCdkV1A',
    },
];
